name: Build APK Stable

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer:latest
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean old builds
        run: rm -rf .buildozer bin

      - name: Build APK (stable mode)
        run: yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
